from reclaim_sdk.models.task import ReclaimTask
from reclaim_sdk.client import ReclaimClient
from datetime import datetime, timedelta

token = "eyJhbGciOiJIUzI1NiJ9.eyJhdF9oYXNoIjoiN2lrSXVSSHB6UkFvMkw1SnJFWUVwZyIsInN1YiI6IjEwOTY1NTYwMjcxMzkyODkzMDU3MSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJyb2xlcyI6W10sImlzcyI6InJlY2xhaW0tYXBpIiwiZ2l2ZW5fbmFtZSI6IkVzdGVhayIsImxvY2FsZSI6ImVuIiwibm9uY2UiOiJjY2IxYzYyZS1jYTU4LTQwZWEtOTMzYS0zZGVmMGZkNGJkN2MiLCJwaWN0dXJlIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUxtNXd1MFhxUHQ3WGRUd1dLeFZiYW93R2tKa0VxSVJOZFVRbEpLcWlQbG9iQT1zOTYtYyIsIm5iZiI6MTY2ODcyNjY3NCwiYXpwIjoiMjIwOTM4MDgyMDI3LWdrYzg1ZGIxZHVldWJyNTQ0cHM5c3ZndGxlYzQ2MDhsLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwibmFtZSI6IkVzdGVhayBTaGFwaW4iLCJzdGF0ZSI6eyJhcHAiOiJhcHAiLCJhcHBVcmwiOiJodHRwczovL2FwcC5yZWNsYWltLmFpLyIsInJlZiI6bnVsbCwic2xhY2tUZWFtSWQiOm51bGwsInNsYWNrVXNlcklkIjpudWxsLCJyZWRpcmVjdCI6Ii9wbGFubmVyPyIsImppcmFTdGF0ZSI6bnVsbCwib3JpZ2luYWxVcmkiOm51bGwsInJlZGlyZWN0VXJpIjoiaHR0cHM6Ly9hcGkuYXBwLnJlY2xhaW0uYWkvb2F1dGgvY2FsbGJhY2svZ29vZ2xlIiwiaW52aXRlS2V5IjpudWxsLCJ1dG1DYW1wYWlnbiI6bnVsbCwidXRtTWVkaXVtIjpudWxsLCJ1dG1UZXJtIjpudWxsLCJyc3ZwIjpudWxsLCJvbmVPbk9uZUlkIjpudWxsLCJub25jZSI6IjEyNjI2MTkwLTIxNjktNGFlYS05Yjk2LWQ3YjQ1ZjMwMTMxMSJ9LCJleHAiOjE2NjkzMzE0NzQsImlhdCI6MTY2ODcyNjY3NCwiZmFtaWx5X25hbWUiOiJTaGFwaW4iLCJlbWFpbCI6ImVzdGVha3NoYXBpbkBnbWFpbC5jb20iLCJvYXV0aDJQcm92aWRlciI6Imdvb2dsZSJ9.xHcP5HSmLpc3LWApAh5NNo4SOYLGdvBaW2L-s8R4lLk"

ReclaimClient(token=token)

# It is also possible to create an object without using a context manager.
task = ReclaimTask()

task.name = "test_task_12345"
task.duration = 5
task.min_work_duration = 0.75
task.max_work_duration = 2
task.start_date = datetime.now() + timedelta(days=3)
task.due_date = datetime.now() + timedelta(days=5)

# Then the object needs to be saved manually to the API.
task.save()
